replicaCount: 2

image:
  repository: YOUR_DOCKERHUB_USERNAME/nexvion
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30080
  metricsPort: 9113

ingress:
  enabled: true
  className: traefik
  host: nexvion.local

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

metricsExporter:
  image: nginx/nginx-prometheus-exporter:1.3.0
  resources:
    requests:
      cpu: 10m
      memory: 16Mi
    limits:
      cpu: 50m
      memory: 32Mi

# Creates a ServiceMonitor only if the Prometheus Operator CRDs are installed
serviceMonitor:
  enabled: true
  interval: 15s
  release: kps
