# --- Local VirtualBox VM (Ansible chalega isi VM par) ---
[local_vm]
nexvion-vm ansible_host=127.0.0.1 ansible_connection=local ansible_user=prakash

# --- AWS EC2 (terraform output ke baad IP yahan daalo, line uncomment karo) ---
[aws]
# nexvion-aws ansible_host=<EC2_PUBLIC_IP> ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/nexvion-key

[devops:children]
local_vm
aws
